"""Agregar relacion usuario paciente

Revision ID: 52aed51e1777
Revises: 90f9e09bed4f
Create Date: 2026-10-02 17:55:07.768896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52aed51e1777'
down_revision: Union[str, Sequence[str], None] = '90f9e09bed4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('usuario_id_FK', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'pacientes', ['usuario_id_FK'])
    op.create_foreign_key(None, 'pacientes', 'usuarios', ['usuario_id_FK'], ['id_PK'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'pacientes', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'pacientes', type_='unique')
    op.drop_column('pacientes', 'usuario_id_FK')
    # ### end Alembic commands ###
