"""crear tablas restantes de VITALIA

Revision ID: 90f9e09bed4f
Revises: f19de211b53c
Create Date: 2026-09-25 12:01:32.237664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f9e09bed4f'
down_revision: Union[str, Sequence[str], None] = 'f19de211b53c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alergias',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('severidad', sa.String(length=50), nullable=True),
    sa.Column('tipo_alergia', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('eventos_calendario',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('todo_el_dia', sa.Boolean(), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('tipo_evento', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('medicamentos',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('principio_activo', sa.String(length=200), nullable=True),
    sa.Column('presentacion', sa.String(length=100), nullable=True),
    sa.Column('requiere_receta', sa.Boolean(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('codigo_barras', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('pacientes',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('apellido', sa.String(length=150), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('correo_electronico', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('proveedores',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo_electronico', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('salas',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('piso', sa.String(length=20), nullable=True),
    sa.Column('lista_equipamiento', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('tipos_movimiento_inventario',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('alergias_paciente',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paciente_id_FK', sa.Integer(), nullable=False),
    sa.Column('alergia_id_FK', sa.Integer(), nullable=False),
    sa.Column('severidad', sa.String(length=50), nullable=True),
    sa.Column('fecha_diagnostico', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alergia_id_FK'], ['alergias.id_PK'], ),
    sa.ForeignKeyConstraint(['paciente_id_FK'], ['pacientes.id_PK'], ),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('equipamiento_sala',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sala_id_FK', sa.Integer(), nullable=True),
    sa.Column('nombre_equipo', sa.String(length=200), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_compra', sa.Date(), nullable=True),
    sa.Column('ultimo_mantenimiento', sa.Date(), nullable=True),
    sa.Column('proximo_mantenimiento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['sala_id_FK'], ['salas.id_PK'], ),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('interacciones_medicamentos',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medicamento_id_FK', sa.Integer(), nullable=True),
    sa.Column('medicamento_interactuante_id_FK', sa.Integer(), nullable=True),
    sa.Column('severidad', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('nivel_evidencia', sa.String(length=100), nullable=True),
    sa.Column('accion_requerida', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['medicamento_id_FK'], ['medicamentos.id_PK'], ),
    sa.ForeignKeyConstraint(['medicamento_interactuante_id_FK'], ['medicamentos.id_PK'], ),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('inventario',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medicamento_id_FK', sa.Integer(), nullable=True),
    sa.Column('numero_lote', sa.String(length=100), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=True),
    sa.Column('ubicacion', sa.String(length=150), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('proveedor_id_FK', sa.Integer(), nullable=True),
    sa.Column('fecha_recepcion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['medicamento_id_FK'], ['medicamentos.id_PK'], ),
    sa.ForeignKeyConstraint(['proveedor_id_FK'], ['proveedores.id_PK'], ),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('movimientos_inventario',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventario_id_FK', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('tipo_movimiento_FK', sa.Integer(), nullable=True),
    sa.Column('usuario_id_FK', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('id_referencia', sa.Integer(), nullable=True),
    sa.Column('stock_anterior', sa.Integer(), nullable=True),
    sa.Column('stock_nuevo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventario_id_FK'], ['inventario.id_PK'], ),
    sa.ForeignKeyConstraint(['tipo_movimiento_FK'], ['tipos_movimiento_inventario.id_PK'], ),
    sa.ForeignKeyConstraint(['usuario_id_FK'], ['usuarios.id_PK'], ),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('notificaciones',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id_FK', sa.Integer(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('enlace', sa.String(length=255), nullable=True),
    sa.Column('leido_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id_FK'], ['usuarios.id_PK'], ),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('registros_auditoria',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id_FK', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=True),
    sa.Column('id_registro', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('marca_tiempo', sa.DateTime(), nullable=False),
    sa.Column('nombre_tabla', sa.String(length=100), nullable=True),
    sa.Column('valores_antiguos', sa.JSON(), nullable=True),
    sa.Column('valores_nuevos', sa.JSON(), nullable=True),
    sa.Column('direccion_ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id_FK'], ['usuarios.id_PK'], ),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('citas',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paciente_id_FK', sa.Integer(), nullable=True),
    sa.Column('doctor_id_FK', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('evento_calendario_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_PK'], ),
    sa.ForeignKeyConstraint(['doctor_id_FK'], ['doctores.id_PK'], ),
    sa.ForeignKeyConstraint(['evento_calendario_id'], ['eventos_calendario.id_PK'], ),
    sa.ForeignKeyConstraint(['paciente_id_FK'], ['pacientes.id_PK'], ),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('contratos_doctor',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id_FK', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('tipo_contrato', sa.String(length=50), nullable=True),
    sa.Column('salario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('url_documento', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id_FK'], ['doctores.id_PK'], ),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('doctor_especialidades',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id_FK', sa.Integer(), nullable=False),
    sa.Column('especialidad_id_FK', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id_FK'], ['doctores.id_PK'], ),
    sa.ForeignKeyConstraint(['especialidad_id_FK'], ['especialidades.id_PK'], ),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('historial_medico',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paciente_id_FK', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_diagnostico', sa.Date(), nullable=True),
    sa.Column('tratamiento', sa.Text(), nullable=True),
    sa.Column('doctor_id_FK', sa.Integer(), nullable=True),
    sa.Column('tipo_sangre', sa.String(length=10), nullable=True),
    sa.Column('nombre_contacto_emergencia', sa.String(length=150), nullable=True),
    sa.Column('telefono_contacto_emergencia', sa.String(length=20), nullable=True),
    sa.Column('proveedor_seguro_id_FK', sa.Integer(), nullable=True),
    sa.Column('numero_poliza_seguro', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id_FK'], ['doctores.id_PK'], ),
    sa.ForeignKeyConstraint(['paciente_id_FK'], ['pacientes.id_PK'], ),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('registros_medicos',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paciente_id_FK', sa.Integer(), nullable=False),
    sa.Column('tipo_registro', sa.String(length=100), nullable=True),
    sa.Column('notas_generales', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('doctor_id_FK', sa.Integer(), nullable=True),
    sa.Column('url_adjunto', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id_FK'], ['doctores.id_PK'], ),
    sa.ForeignKeyConstraint(['paciente_id_FK'], ['pacientes.id_PK'], ),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('colas',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cita_id_FK', sa.Integer(), nullable=True),
    sa.Column('paciente_id_FK', sa.Integer(), nullable=True),
    sa.Column('doctor_id_FK', sa.Integer(), nullable=True),
    sa.Column('numero_cola', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('hora_registro', sa.DateTime(), nullable=True),
    sa.Column('prioridad', sa.String(length=50), nullable=True),
    sa.Column('hora_llamado', sa.DateTime(), nullable=True),
    sa.Column('numero_consultorio', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cita_id_FK'], ['citas.id_PK'], ),
    sa.ForeignKeyConstraint(['doctor_id_FK'], ['doctores.id_PK'], ),
    sa.ForeignKeyConstraint(['paciente_id_FK'], ['pacientes.id_PK'], ),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('consultas',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cita_id_FK', sa.Integer(), nullable=True),
    sa.Column('paciente_id_FK', sa.Integer(), nullable=True),
    sa.Column('doctor_id_FK', sa.Integer(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('tratamiento', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_visita', sa.DateTime(), nullable=True),
    sa.Column('signos_vitales', sa.JSON(), nullable=True),
    sa.Column('fecha_proxima_cita', sa.Date(), nullable=True),
    sa.Column('codigo_cie10', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cita_id_FK'], ['citas.id_PK'], ),
    sa.ForeignKeyConstraint(['doctor_id_FK'], ['doctores.id_PK'], ),
    sa.ForeignKeyConstraint(['paciente_id_FK'], ['pacientes.id_PK'], ),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('recetas',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paciente_id_FK', sa.Integer(), nullable=True),
    sa.Column('doctor_id_FK', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('consulta_id_FK', sa.Integer(), nullable=True),
    sa.Column('codigo_qr', sa.String(length=255), nullable=True),
    sa.Column('hash_firma', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id_FK'], ['consultas.id_PK'], ),
    sa.ForeignKeyConstraint(['doctor_id_FK'], ['doctores.id_PK'], ),
    sa.ForeignKeyConstraint(['paciente_id_FK'], ['pacientes.id_PK'], ),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('items_receta',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receta_id_FK', sa.Integer(), nullable=True),
    sa.Column('medicamento_id_FK', sa.Integer(), nullable=True),
    sa.Column('dosis', sa.String(length=100), nullable=True),
    sa.Column('frecuencia', sa.String(length=100), nullable=True),
    sa.Column('duracion', sa.String(length=100), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('instrucciones', sa.Text(), nullable=True),
    sa.Column('via_administracion', sa.String(length=100), nullable=True),
    sa.Column('recargas_permitidas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medicamento_id_FK'], ['medicamentos.id_PK'], ),
    sa.ForeignKeyConstraint(['receta_id_FK'], ['recetas.id_PK'], ),
    sa.PrimaryKeyConstraint('id_PK')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_receta')
    op.drop_table('recetas')
    op.drop_table('consultas')
    op.drop_table('colas')
    op.drop_table('registros_medicos')
    op.drop_table('historial_medico')
    op.drop_table('doctor_especialidades')
    op.drop_table('contratos_doctor')
    op.drop_table('citas')
    op.drop_table('registros_auditoria')
    op.drop_table('notificaciones')
    op.drop_table('movimientos_inventario')
    op.drop_table('inventario')
    op.drop_table('interacciones_medicamentos')
    op.drop_table('equipamiento_sala')
    op.drop_table('alergias_paciente')
    op.drop_table('tipos_movimiento_inventario')
    op.drop_table('salas')
    op.drop_table('proveedores')
    op.drop_table('pacientes')
    op.drop_table('medicamentos')
    op.drop_table('eventos_calendario')
    op.drop_table('alergias')
    # ### end Alembic commands ###
