"""crear tablas iniciales de usuarios

Revision ID: f19de211b53c
Revises: 
Create Date: 2026-09-25 11:41:56.284731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19de211b53c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidades',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('roles',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_PK')
    )
    op.create_table('usuarios',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('correo_electronico', sa.String(length=150), nullable=False),
    sa.Column('hash_contrasena', sa.String(length=255), nullable=False),
    sa.Column('rol_id_FK', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('token_restablecimiento', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['rol_id_FK'], ['roles.id_PK'], ),
    sa.PrimaryKeyConstraint('id_PK'),
    sa.UniqueConstraint('correo_electronico')
    )
    op.create_table('doctores',
    sa.Column('id_PK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id_FK', sa.Integer(), nullable=True),
    sa.Column('especialidad_id_FK', sa.Integer(), nullable=True),
    sa.Column('numero_licencia', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('costo_consulta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ruta_firma', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['especialidad_id_FK'], ['especialidades.id_PK'], ),
    sa.ForeignKeyConstraint(['usuario_id_FK'], ['usuarios.id_PK'], ),
    sa.PrimaryKeyConstraint('id_PK'),
    sa.UniqueConstraint('usuario_id_FK')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctores')
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('especialidades')
    # ### end Alembic commands ###
